---
title: "maximum likelihood function"
author: "Xin"
editor: visual
date: today
toc: true
execute: 
  echo: true
number-sections: true
highlight-style: pygments
format: 
  html:
    code-fold: true
  pdf: 
    geometry: 
      - top=30mm
      - left=30mm
  docx: default
---

Formulate the model for Poisson regression with year as predictor.

$$
Y|x_i \sim Po(\lambda(x_i))
$$

$$
\lambda(x_i)= e^{\beta_0+\beta_1x_{i1}+...+\beta_px_{ip}}
$$

Maximum likelihood estimation: $$
\hat{\theta} = argmax\;log\;l(\theta)
$$ Likelihood function for the Possion GLM $$
log\;l(y|\beta_0,\beta1,...,\beta_p,x)=\sum_{i=1}^{n}[-\lambda(x_i)+y_ilog(\lambda(x_i))-log(y_i!)]
$$

```{r}
df <- read.csv("bird_count.csv")

beta <- rep(0, 2)  
X <- as.matrix(cbind(1, df$yr))

log_likelihood_function <- function(params) {
  lambda <- exp(X %*% params)
  log_likelihood <- sum(df$count * log(lambda) - lambda - lfactorial(df$count))
  return(-log_likelihood)  
}

result <- optim(par = beta, fn = log_likelihood_function, method = "BFGS")

result$par
```

**Answer**: $\beta_0=1.95$, $\beta_1=8.32e^{-5}$. So, $\hat{\lambda(x)}=e^{1.95+0.0000832x}$

```{r}

mylist <- lapply(1:3,function(iter){
years <- 1999:2012
X_new <- as.matrix(cbind(1, years))
beta <- c(1.948875, 8.323285e-05)
lambda_new <- exp(X_new %*% beta)

count_new <- rpois(n = length(years), lambda = lambda_new)

samples_df <- data.frame(
  Year = years,
  Count = count_new,iter=iter)
return(samples_df)
})

df_tosave = do.call('rbind',mylist)
write.csv(df_tosave, file = "hypothetical_observations.csv", row.names = FALSE)
```
